# -*- coding: utf-8 -*-
"""user input(2.1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yC6jL_UEZ13qCiv4MqLA4hm4mkIIRUU-

Write a program that uses input to prompt a user for their name and then welcomes them
"""

name = input("Enter your name: ")
print("Welcome,",name)