# -*- coding: utf-8 -*-
"""Hello_world.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WhiLqgGIyVyNf7CX4U7PEi3C17uf2KbO

The very first program in python language. Welcome to the world of Python programming
"""

print('Hello world!')
print('Welcome to the world of Python programming..')